### ISSUE TITLE
Support for gmsp

### ISSUE THREAD

**Issue by RhinoCD** [quantiom/AdvancedVanish#12]
This is a bit confusing, but it would be cool if support for gmsp was added. So I have staff who has access to gmsp, and vanish, but not /fly as I don't want staff abusing /fly. When in vanish they can fly but can't build, and can use gmsp to see through caves and blocks, etc.

It would be cool if support for gmsp, when a player goes out of vanish while in gmsp, their fly doesn't get disabled, as when they leave vanish, they start plummeting to the void.

I would give staff the "Keep-Fly" permission, but that would mean, when staff goes into vanish, than goes out of vanish, they would be able to fly while not in vanish, and would have to type /fly to exit fly again.

**Comment by quantiom** [comment]
Hmm, I see what you mean. I think this is kind of a very specific request because I assume you have something else that disables their fly after they get out of the spectator game mode, right? I could add this, but I don't think I'll add something that disables fly when a player changes their game mode from spectator to survival or adventure because that's not really related to this plugin.

**Comment by RhinoCD** [comment]
no, I don't have anything that disables their fly when they get out of spectator mode. Default spectator mode puts the player in fly, and takes them out of fly after they go in gms, its just default gmsp / spectator mode. Its just when they unvanish, it switches their fly off which plummets them into the void.
